### ISSUE TITLE
How will single vs multiple site details work?

### ISSUE THREAD

**Issue by colmjude** [digital-land/planning-application-data-specification#306]
This component is listed for householder and many other types, but the information model only refers to the two tree works applciation types.
Need some clarity on how this is intended to work for 'single' location sites for all other types.

_Originally posted by @James-Planningportal in https://github.com/digital-land/planning-application-data-specification/discussions/70#discussioncomment-13002890_

**Comment by colmjude** [comment]
We should be able to handle it in the validation rules.
For example, `tree-works` applications **must** have 1 or more sites.
Other application types **must** have 1 site.

We could capture a count-constraint condition something like this for `tree-work` applications:
```
   - rule: 
      description: "At least one site-location must be provided for tree works applications"
      type: count-constraint
      field: site-locations
      when:
        application-type:
          in: [tree-works]
      require:
        min: 1
```

And to handle all other applications, something like
```
  - rule: 
      description: "Exactly one site-location for all other applications types"
      type: count-constraint
      field: site-locations
      when:
        application-type:
          not: [tree-works]
      require:
        exact: 1
```
