### ISSUE TITLE
Outline application templates specify an 'Unknown' option in industrial machinery section

### ISSUE THREAD

**Issue by colmjude** [digital-land/planning-application-data-specification#316]
In the [Industrial or commercial processes and machinery module](https://github.com/digital-land/planning-application-data-specification/discussions/95)

Application templates specify an 'Unknown' option for:

- 'proposal-waste-management' (Yes/No/Unknown)
- In 'waste-management': for 'total-capacity' and 'annual-throughput'

that is specific to the two 'Outline planning permission' types.

![image](https://github.com/user-attachments/assets/4683e2d1-58f6-45f6-83ab-2b894868d915)

_Originally posted by @James-Planningportal in https://github.com/digital-land/planning-application-data-specification/discussions/95#discussioncomment-13090926_

**Comment by colmjude** [comment]
We've tried to handle this variance with these commits that add the fields

* `proposal-waste-management-outline` for handling outline variance
* `is-total-capacity-known` and `is-annual-throughput-known`

See commits
* 3fd5e22251f66fb0c9f123f6f2e022e800247e12
* a08dfbdc0fb915ef8e750fbfb803ce2382ff0224
* 83718a950843ee9d91a165aed925d1c2061f0879

This does lead to a more complicated set of field requirement conditions. E.g.
```
  - field: annual-throughput
    required-if:
      - field: not-applicable
        value: false
      - field: is-annual-throughput-known
        value: true
        applies-if:
          - application-type:
            in: [outline]
```

However, an alternative could be to default `is-annual-throughput-known` to True for all applications other than `outline`

**Comment by colmjude** [comment]
The conditions determining if certain fields of this module are required were getting quite complicated because they are different depending on the application type.

Therefore we've decided to simplify things by creating a specific module that can be used in Outline applications.

We now have one module with `full` and `extract-gas-oil` applications that looks like this
```
---
module: processes-machinery-waste
name: Processes machinery waste
description: |
  Information about site activities, processes, and waste management development
  including facility types, capacities, and throughput details
fields:
  - field: site-activity-details
    required: true
  - field: proposal-waste-management
    required: true
  - field: waste-management
  - field: waste-streams
validation:
  ...
entry-date: 2025-07-09
end-date: ''
---
```

With the simplified waste-management substructure looking like this

```
---
component: waste-management
name: Waste management
description: |
  Details of waste management facilities including type, capacity, and throughput information
fields:
  - field: waste-management-facility-type
    required: true
  - field: not-applicable
  - field: total-capacity
    required-if:
      - field: not-applicable
        value: false
  - field: annual-throughput
    required-if:
      - field: not-applicable
        value: false
entry-date: 2025-07-09
end-date: ''
---
```

And the new `processes-machinery-waste-outline` module , looking like this

```
---
module: processes-machinery-waste-outline
name: Processes machinery waste
description: |
  Information about site activities, processes, and waste management development
  including facility types, capacities, and throughput details. Specifically for outline applications
fields:
  - field: site-activity-details
    required: true
  - field: proposal-waste-management-outline
    required: true
  - field: waste-management-outline
  - field: waste-streams
validation:
  - description: "waste-management-outline is required when proposal-waste-management-outline is true"
    rule: "if proposal-waste-management-outline == true then waste-management-outline is required"
  - description: "waste-streams is required when proposal-waste-management-outline is true"
    rule: "if proposal-waste-management-outline == true then waste-streams is required"
entry-date: 2025-07-14
end-date: ''
---
```


With the waste-management-outline substructure looking like this
```
---
component: waste-management-outline
name: Waste management
description: |
  Details of waste management facilities including type, capacity, and throughput information. Specifically for outline applications
fields:
  - field: waste-management-facility-type
    required: true
  - field: not-applicable
  - field: is-total-capacity-known
    required: true
  - field: total-capacity
    required-if:
      - field: not-applicable
        value: false
      - field: is-total-capacity-known
        value: true
  - field: is-annual-throughput-known
    required: true
  - field: annual-throughput
    required-if:
      - field: not-applicable
        value: false
      - field: is-annual-throughput-known
        value: true
entry-date: 2025-07-09
end-date: ''
---
```


See commit 9b05a03f9a701348424b55732a96444a5f4ba832
